//! Parser for `.bsn` source text.
//!
//! The grammar rules track the dynamic-BSN grammar from bevyengine/bevy#23576
//! (plus the jackdaw `map[...]` literal and duplicate-field rejection); the
//! parser builds the editor document types directly, so its output is a
//! [`SceneBsnAst`] with no separate parse-time representation.
//!
//! There is no tuple literal. A Rust tuple is written as a list, and a list of
//! pairs as a list of two-element lists: `[["class", "Mage"]]`, never
//! `[("class", "Mage")]`, which fails at the `(`. The emitter writes that shape
//! (see `document::from_reflect`), so this constrains hand-authored text.

use std::cell::RefCell;

use bevy_ecs::entity::Entity;
use lalrpop_util::lalrpop_mod;
use thiserror::Error;

use crate::document::{BsnField, BsnPatch, BsnStructData, BsnValue, SceneBsnAst};

pub mod lexer;

lalrpop_mod!(
    #[allow(
        clippy::all,
        clippy::pedantic,
        clippy::restriction,
        clippy::nursery,
        unused_qualifications,
        reason = "generated by lalrpop"
    )]
    grammar,
    "/parse/grammar.rs"
);

/// An error produced while parsing `.bsn` source text.
#[derive(Error, Debug)]
pub enum ParseError {
    /// The lexer hit a character it could not turn into a token.
    #[error("lex error: unexpected character {0:?}")]
    Lex(char),
    /// The grammar rejected the token stream.
    #[error("parse error: {0}")]
    Parse(String),
    /// A struct gave the same field name twice.
    #[error("duplicate field '{field}' in '{type_name}'")]
    DuplicateField {
        /// The struct the field was written twice in.
        type_name: String,
        /// The field written twice.
        field: String,
    },
}

/// Parse `.bsn` source text into a document, returning the document and the
/// entity of the top-level patch group (which may be a multi-root `Children`
/// wrapper; the loader unwraps it).
pub fn parse_bsn(text: &str) -> Result<(SceneBsnAst, Entity), ParseError> {
    let ast = RefCell::new(SceneBsnAst::default());

    let lexer = lexer::Lexer::new(text);
    match grammar::TopLevelPatchesParser::new().parse(&ast, lexer) {
        Ok(root) => {
            let mut ast = ast.into_inner();
            check_duplicate_fields(&mut ast)?;
            Ok((ast, root))
        }
        Err(err) => {
            if let lalrpop_util::ParseError::User {
                error: lexer::Error::UnexpectedChar(c),
            } = err
            {
                Err(ParseError::Lex(c))
            } else {
                Err(ParseError::Parse(format!("{err:?}")))
            }
        }
    }
}

/// Reject structs that name the same field twice: applying such a patch
/// would silently let the last occurrence win, hiding hand-edit mistakes.
fn check_duplicate_fields(ast: &mut SceneBsnAst) -> Result<(), ParseError> {
    fn find_duplicate(data: &BsnStructData) -> Option<ParseError> {
        let mut seen = std::collections::HashSet::new();
        for BsnField { name, value } in &data.fields.0 {
            if !seen.insert(name.as_str()) {
                return Some(ParseError::DuplicateField {
                    type_name: data.type_path.clone(),
                    field: name.clone(),
                });
            }
            if let Some(err) = find_duplicate_in_value(value) {
                return Some(err);
            }
        }
        None
    }

    fn find_duplicate_in_value(value: &BsnValue) -> Option<ParseError> {
        match value {
            BsnValue::Struct(data) => find_duplicate(data),
            BsnValue::TupleStruct(data) => data.values.iter().find_map(find_duplicate_in_value),
            BsnValue::List(items) => items.iter().find_map(find_duplicate_in_value),
            BsnValue::Map(entries) => entries.iter().find_map(|(k, v)| {
                find_duplicate_in_value(k).or_else(|| find_duplicate_in_value(v))
            }),
            _ => None,
        }
    }

    let mut patches = ast.world.query::<&BsnPatch>();
    for patch in patches.iter(&ast.world) {
        let found = match patch {
            BsnPatch::Struct(data) => find_duplicate(data),
            BsnPatch::Template(_, Some(fields)) => fields
                .0
                .iter()
                .find_map(|f| find_duplicate_in_value(&f.value)),
            BsnPatch::TupleStruct(data) => data.values.iter().find_map(find_duplicate_in_value),
            _ => None,
        };
        if let Some(err) = found {
            return Err(err);
        }
    }
    Ok(())
}
