[package]
name = "bevy_time"
version = "0.13.1"
edition = "2021"
description = "Provides time functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default = []
serialize = ["serde"]
bevy_ci_testing = ["bevy_app/bevy_ci_testing"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.13.1" }
bevy_ecs = { path = "../bevy_ecs", version = "0.13.1", features = [
  "bevy_reflect",
] }
bevy_reflect = { path = "../bevy_reflect", version = "0.13.1", features = [
  "bevy",
] }
bevy_utils = { path = "../bevy_utils", version = "0.13.1" }

# other
crossbeam-channel = "0.5.0"
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "1.0"

[lints]
workspace = true
