// GPU-authored ("procedural") cluster meshes — persistent geometry whose topology
// is CPU-authored but whose vertex payload is generated by a downstream compute
// pass (planet terrain patches, ocean shells, …). The static-asset upload path is
// reused for everything CPU-known (indices, cluster records, groups); the vertex
// pools get *reservations* instead of writes, and the CLAS comes from
// pre-built shared topology templates (`INSTANTIATE_TRIANGLE_CLUSTER`) instead of
// a per-mesh direct build — so streaming a procedural mesh never takes the
// per-mesh `poll(Wait)` the direct CLAS build does. Instantiated CLAS addresses
// land in the standard `ClasArena::cluster_clas_addresses` table (the instantiate
// offsets restore global cluster/geometry ids), so the downstream
// selector → blas_rebuild → PTLAS path and the bindless chit resolve are
// completely unchanged — the template→instantiate 1:1 equivalence with the
// direct build was proven during the Phase 2a A/B bring-up (since removed).
//
// Per-frame flow (all in the `RenderGraph` schedule, before
// `SolariClusterSystems::Scatter`):
//   1. Extract/bind: `queue_upload_if_needed` sees `ClusterMesh::gpu_authored`,
//      reserves vertex-pool ranges, uploads topology, queues a pending entry
//      (instead of `pending_clas_uploads`).
//   2. `drain_pending_procedural` (Fill set, first): publishes the reserved
//      ranges to `ProceduralMeshRanges` + `ProceduralFillQueue`, building the
//      shared template set for new `(topology, band)` keys (one-time stall each).
//   3. The USER's fill system (also `SolariProceduralSystems::Fill`, after
//      `drain_pending_procedural`): drains its assets from `ProceduralFillQueue`,
//      dispatches its generation compute writing the reserved vertex ranges
//      (encoder submitted immediately, NOT deferred), then pushes the asset ids
//      into `ProceduralInstantiateQueue`.
//   4. `instantiate_procedural` (Instantiate set): CPU-writes the per-cluster
//      `InstantiateClusterInfoNV` descriptors (template addresses are CPU-known
//      from the one-time set build), records one `INSTANTIATE_TRIANGLE_CLUSTER`
//      op per mesh into per-mesh CLAS slabs, submits, and reports the mesh
//      ready through `ProceduralReadyChannel`.
#![allow(unsafe_code, reason = "raw-VK cluster-AS template instantiate")]

use ash::vk::{self, TaggedStructure};
use bevy_asset::AssetId;
use bevy_ecs::{
    prelude::*,
    schedule::SystemSet,
};
use bevy_math::Vec3;
use bevy_platform::collections::HashMap;
use bevy_render::{
    render_resource::Buffer,
    renderer::{RenderDevice, RenderQueue},
};
use core::ops::Range;
use range_alloc::RangeAllocator;
use std::sync::{Arc, Mutex};
use wgpu::CommandEncoderDescriptor;

use super::clas_arena::{
    ClasArena, CLAS_SCRATCH_ALIGN, CLAS_STORAGE_ALIGN,
};
use super::{Cluster, ClusterIndex, ClusterMesh, ClusterMeshManager};
use crate::gpu::allocator::{Allocator, MemoryLocation, SparseBuffer};
use crate::gpu::retire::GpuRetire;
use crate::gpu::extension::{
    cmd_build_cluster_acceleration_structures_indirect, cmd_global_as_barrier,
    ClusterExtensionFns,
};

/// Virtual address space reserved for the procedural CLAS slab arena — 8 GB,
/// sparse-backed (only committed pages cost memory). Slabs are fixed-size per
/// `(topology, band)`, so the allocator never fragments.
const PROCEDURAL_CLAS_VIRTUAL_BYTES: u64 = 8 * 1024 * 1024 * 1024;

const INDEX_TYPE_32BIT: u32 = 4;
const OPAQUE_GEOMETRY_FLAG: u8 = 0b100;

/// Runtime-only marker on a [`ClusterMesh`] declaring its vertex payload
/// GPU-authored. Never serialized (`.cluster_mesh` assets are always CPU-baked).
#[derive(Clone, Copy, Debug)]
pub struct ProceduralMeshInfo {
    /// Identifies the shared topology (canonical clusters + indices) this mesh
    /// instantiates — must be registered in [`ProceduralClusters`] before the
    /// mesh binds. All meshes with one key have IDENTICAL cluster
    /// vertex/index offsets and counts; only vertex payloads (and per-cluster
    /// `bounds_sphere`) differ.
    pub topology_key: u64,
    /// Scale band selecting the template set (`instantiationBoundingBoxLimit`
    /// is baked per band — patch extents spanning orders of magnitude can't
    /// share one bbox without wrecking instantiate sizing). Semantics are the
    /// registrant's (e.g. quadtree depth, bucketed by planet radius).
    pub band: u32,
    /// Conservative MESH-LOCAL AABB covering every mesh in this
    /// `(topology_key, band)` — the template's instantiation bbox limit.
    /// Vertex positions the fill pass writes MUST stay inside it.
    pub band_aabb_min: [f32; 3],
    pub band_aabb_max: [f32; 3],
}

/// A shared canonical topology, registered once per distinct patch layout.
#[derive(Clone)]
pub struct ProceduralTopology {
    /// Canonical cluster records with MESH-LOCAL `vertex_offset`/`index_offset`.
    /// `bounds_sphere` is ignored here (per-mesh records carry the real bounds).
    pub clusters: Arc<[Cluster]>,
    /// Canonical index content (mesh-local values, matching `clusters`).
    pub indices: Arc<[u32]>,
    /// Reference vertex positions for the template build (canonical domain,
    /// e.g. the unit patch grid). Length = sum of cluster `vertex_count`s.
    pub reference_positions: Arc<[Vec3]>,
}

/// Reserved pool ranges for one pending/live procedural mesh — what a fill
/// system needs to target its writes. Element (not byte) bases.
#[derive(Clone, Copy, Debug)]
pub struct ProceduralRanges {
    pub topology_key: u64,
    pub band: u32,
    /// First element in `vertex_positions`/`vertex_normals`/`vertex_tangents`/
    /// `vertex_uvs`/`vertex_custom`/`vertex_packed` (all pools share the index).
    pub vertex_base: u32,
    pub vertex_count: u32,
    pub index_base: u32,
    pub cluster_base: ClusterIndex,
    pub cluster_count: u32,
}

/// A procedural mesh whose pools were reserved at bind time, awaiting range
/// publication + template-set assurance. Queued by
/// `ClusterMeshManager::queue_upload_if_needed`, drained by
/// [`drain_pending_procedural`].
pub struct ProceduralPendingUpload {
    pub asset_id: AssetId<ClusterMesh>,
    pub ranges: ProceduralRanges,
    pub band_aabb_min: [f32; 3],
    pub band_aabb_max: [f32; 3],
}

/// System sets for the procedural flow, chained in the `RenderGraph` schedule
/// before `SolariClusterSystems::Scatter`: `Reserve` publishes this frame's
/// reserved meshes (+ builds missing template sets), USER fill systems go in
/// `Fill` (dispatch generation compute, submit immediately, push to
/// [`ProceduralInstantiateQueue`]), `Instantiate` builds their CLAS.
#[derive(SystemSet, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SolariProceduralSystems {
    Reserve,
    Fill,
    Instantiate,
}

/// Assets whose ranges are reserved and topology uploaded, awaiting their fill
/// dispatch. A fill system drains the ids it recognizes; unrecognized ids stay
/// queued (warned about if they linger — see [`instantiate_procedural`]).
#[derive(Resource, Default)]
pub struct ProceduralFillQueue(pub Vec<AssetId<ClusterMesh>>);

/// Assets whose vertex ranges were written this frame (fill dispatch submitted),
/// ready for CLAS instantiation. Pushed by user fill systems.
#[derive(Resource, Default)]
pub struct ProceduralInstantiateQueue(pub Vec<AssetId<ClusterMesh>>);

/// Reserved ranges per live procedural mesh, keyed by asset — the join table
/// between solari's reservation and the user's fill dispatch.
#[derive(Resource, Default)]
pub struct ProceduralMeshRanges(pub HashMap<AssetId<ClusterMesh>, ProceduralRanges>);

/// Cross-world "mesh is traceable" handshake: the render world pushes an asset
/// id after its instantiate op is SUBMITTED; the main world drains the shared
/// vec (e.g. to gate quadtree retirement so replaced LOD patches only despawn
/// once their replacements can actually be traced).
#[derive(Resource, Clone, Default)]
pub struct ProceduralReadyChannel(pub Arc<Mutex<Vec<AssetId<ClusterMesh>>>>);

/// One template set: the shared per-cluster CLAS templates for a
/// `(topology_key, band)`, plus the cached instantiate sizing.
struct TemplateSet {
    /// Driver-chosen per-cluster template device addresses (CPU-known after the
    /// one-time build+readback), local cluster order.
    template_addrs: Vec<u64>,
    /// Worst-case CLAS bytes one instantiated mesh needs (aligned slab size).
    clas_slab_size: u64,
    /// Scratch bytes one instantiate op needs.
    op_scratch_size: u64,
    /// Geometry-shape maxima shared by every instantiate of this set.
    max_tris: u32,
    max_verts: u32,
    total_tris: u32,
    total_verts: u32,
    /// Device address of the cached per-op `src_infos_count` buffer
    /// (= cluster_count, identical for every mesh of the set).
    count_addr: vk::DeviceAddress,
    // GPU allocations the templates / instantiate ops keep referencing for the
    // arena's lifetime. Dropping any of these while a template can still be
    // instantiated is UB, so they ride along here.
    _template_storage: wgpu::Buffer,
    _index_buf: Buffer,
    _reference_verts_buf: Buffer,
    _count_buf: Buffer,
}

/// Reused per-batch instantiate inputs, grown on demand (old buffers retired
/// through [`GpuRetire`]) — per-batch dedicated allocations churned the heap.
/// Cross-batch reuse is ordered by the global AS barriers around every op.
#[derive(Default)]
struct BatchBufs {
    src_infos: Option<(Buffer, u64)>,
    /// Capacity is usable bytes AFTER `CLAS_SCRATCH_ALIGN` base alignment.
    scratch: Option<(wgpu::Buffer, u64)>,
    dst_addresses: Option<(wgpu::Buffer, u64)>,
}

impl BatchBufs {
    /// Grow any buffer whose capacity is below this batch's need.
    fn ensure(
        &mut self,
        render_device: &RenderDevice,
        allocator: &Allocator,
        retire: &mut GpuRetire,
        queue: &RenderQueue,
        src_len: u64,
        scratch_len: u64,
        dst_len: u64,
    ) {
        if self.src_infos.as_ref().is_none_or(|(_, cap)| *cap < src_len) {
            let cap = src_len.next_power_of_two().max(64 << 10);
            if let Some((old, _)) = self.src_infos.take() {
                retire.retire(queue, "procedural.instantiate.src_infos", old);
            }
            let buf = render_device.create_buffer(&wgpu::BufferDescriptor {
                label: Some("procedural.instantiate.src_infos"),
                size: cap,
                usage: wgpu::BufferUsages::STORAGE
                    | wgpu::BufferUsages::BLAS_INPUT
                    | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            });
            self.src_infos = Some((buf, cap));
        }
        if self.scratch.as_ref().is_none_or(|(_, cap)| *cap < scratch_len) {
            let cap = scratch_len.next_power_of_two().max(1 << 20);
            if let Some((old, _)) = self.scratch.take() {
                retire.retire(queue, "procedural.instantiate.scratch", old);
            }
            let buf = allocator.create_buffer(
                render_device,
                vk::BufferUsageFlags::STORAGE_BUFFER,
                wgpu::BufferUsages::STORAGE,
                cap + CLAS_SCRATCH_ALIGN - 1,
                MemoryLocation::GpuOnly,
                "procedural.instantiate.scratch",
            );
            self.scratch = Some((buf, cap));
        }
        if self.dst_addresses.as_ref().is_none_or(|(_, cap)| *cap < dst_len) {
            let cap = dst_len.next_power_of_two().max(64 << 10);
            if let Some((old, _)) = self.dst_addresses.take() {
                retire.retire(queue, "procedural.instantiate.dst_addresses", old);
            }
            let buf = allocator.create_buffer(
                render_device,
                vk::BufferUsageFlags::STORAGE_BUFFER
                    | vk::BufferUsageFlags::ACCELERATION_STRUCTURE_STORAGE_KHR
                    | vk::BufferUsageFlags::TRANSFER_SRC,
                wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
                cap,
                MemoryLocation::GpuOnly,
                "procedural.instantiate.dst_addresses",
            );
            self.dst_addresses = Some((buf, cap));
        }
    }

    fn bufs(&self) -> (&Buffer, &wgpu::Buffer, &wgpu::Buffer) {
        (
            &self.src_infos.as_ref().unwrap().0,
            &self.scratch.as_ref().unwrap().0,
            &self.dst_addresses.as_ref().unwrap().0,
        )
    }
}

/// Render-world resource owning the shared topologies, their template sets, and
/// the CLAS slab arena procedural meshes instantiate into.
#[derive(Resource)]
pub struct ProceduralClusters {
    topologies: HashMap<u64, ProceduralTopology>,
    templates: HashMap<(u64, u32), TemplateSet>,
    /// Sparse AS-storage arena for instantiated CLAS. Fixed-size slabs per
    /// `(topology, band)` ⇒ the allocator is effectively a slab allocator.
    slab_storage: SparseBuffer,
    slab_alloc: RangeAllocator<u64>,
    slabs: HashMap<AssetId<ClusterMesh>, Range<u64>>,
    /// Slabs of removed meshes, parked INDEFINITELY: a stale PTLAS slot /
    /// shared-BLAS entry can hold the old CLAS addresses until overwritten, so
    /// reuse device-losts. Real recycling lands with geometry eviction.
    /// Cost ~64–128 KB committed pages per retired patch ([`Self::retired_slab_bytes`]).
    retired_slabs: Vec<Range<u64>>,
    /// Reused instantiate batch inputs (see [`BatchBufs`]).
    batch_bufs: BatchBufs,
}

impl ProceduralClusters {
    fn new(render_device: &RenderDevice, allocator: &Allocator) -> Self {
        Self {
            topologies: HashMap::default(),
            templates: HashMap::default(),
            slab_storage: allocator.create_sparse_buffer(
                render_device,
                vk::BufferUsageFlags::ACCELERATION_STRUCTURE_STORAGE_KHR,
                wgpu::BufferUsages::COPY_DST,
                PROCEDURAL_CLAS_VIRTUAL_BYTES,
                "procedural.clas_slabs",
            ),
            slab_alloc: RangeAllocator::new(0..PROCEDURAL_CLAS_VIRTUAL_BYTES),
            slabs: HashMap::default(),
            retired_slabs: Vec::new(),
            batch_bufs: BatchBufs::default(),
        }
    }

    /// Bytes parked in retired (unreusable) slabs — leak telemetry.
    pub fn retired_slab_bytes(&self) -> u64 {
        self.retired_slabs.iter().map(|r| r.end - r.start).sum()
    }

    /// Register a canonical topology. Call before any mesh with this key binds
    /// (e.g. at startup, or lazily from the same system that creates the
    /// assets). Re-registering an existing key is a no-op.
    pub fn register_topology(&mut self, key: u64, topology: ProceduralTopology) {
        debug_assert_eq!(
            topology.reference_positions.len(),
            topology.clusters.iter().map(|c| c.vertex_count as usize).sum::<usize>(),
            "procedural topology {key:#x}: reference vertex count must equal the sum of cluster vertex counts",
        );
        self.topologies.entry(key).or_insert(topology);
    }

    pub fn topology(&self, key: u64) -> Option<&ProceduralTopology> {
        self.topologies.get(&key)
    }

    /// Live instantiated-slab count (debug/occupancy UI).
    pub fn live_mesh_count(&self) -> usize {
        self.slabs.len()
    }

    /// Retire a removed mesh's CLAS slab. Called from the same asset-event path
    /// that frees the mesh pools (`instance_manager`); parked forever — see
    /// `retired_slabs`.
    pub fn remove(&mut self, asset_id: &AssetId<ClusterMesh>) {
        if let Some(slab) = self.slabs.remove(asset_id) {
            self.retired_slabs.push(slab);
        }
    }

    /// Build (once) the shared template set for `(key, band)` — one
    /// `BUILD_TRIANGLE_CLUSTER_TEMPLATE` submit + poll-wait + address readback,
    /// mirroring `clas_template::upload_mesh_templates`. Deliberately
    /// synchronous: it runs once per distinct patch scale, not per mesh.
    #[allow(clippy::too_many_arguments)]
    fn ensure_template_set(
        &mut self,
        render_device: &RenderDevice,
        render_queue: &RenderQueue,
        allocator: &Allocator,
        fns: &ClusterExtensionFns,
        key: u64,
        band: u32,
        band_aabb_min: [f32; 3],
        band_aabb_max: [f32; 3],
    ) -> bool {
        if self.templates.contains_key(&(key, band)) {
            return true;
        }
        let Some(topology) = self.topologies.get(&key) else {
            tracing::error!(
                target: "bevy_solari",
                "procedural mesh references unregistered topology {key:#x}; it will never become traceable",
            );
            return false;
        };
        let Some(cluster_fns) = fns.cluster.as_ref() else {
            return false;
        };
        let clusters = Arc::clone(&topology.clusters);
        let indices = Arc::clone(&topology.indices);
        let reference_positions = Arc::clone(&topology.reference_positions);
        let cluster_count = clusters.len();
        debug_assert!(cluster_count > 0, "procedural topology {key:#x} has no clusters");

        // Canonical index + reference-vertex buffers the templates bake device
        // addresses of — kept alive in the set for the arena's lifetime.
        let index_buf = render_device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("procedural.template.indices"),
            size: (indices.len() * size_of::<u32>()) as u64,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::BLAS_INPUT
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        render_queue.write_buffer(&index_buf, 0, bytemuck::cast_slice(&indices));
        let index_addr = allocator.wgpu_buffer_device_address(&index_buf).get();

        // Positions are tightly packed vec3 (stride 12), same as the pool.
        // Scaled from the canonical unit domain to the band's real extent —
        // the driver derives per-cluster precision/topology from the reference
        // geometry, so references orders of magnitude smaller than the
        // instantiated positions produce degenerate CLAS.
        let band_extent = (band_aabb_max[0] - band_aabb_min[0])
            .abs()
            .max(1.0);
        let ref_bytes: Vec<u8> = reference_positions
            .iter()
            .flat_map(|p| {
                let s = *p * band_extent;
                [s.x.to_le_bytes(), s.y.to_le_bytes(), s.z.to_le_bytes()]
                    .into_iter()
                    .flatten()
            })
            .collect();
        let ref_verts_buf = render_device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("procedural.template.reference_verts"),
            size: ref_bytes.len() as u64,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::BLAS_INPUT
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        render_queue.write_buffer(&ref_verts_buf, 0, &ref_bytes);
        let ref_verts_addr = allocator.wgpu_buffer_device_address(&ref_verts_buf).get();

        let count_buf = render_device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("procedural.template.count"),
            size: 4,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::BLAS_INPUT
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        render_queue.write_buffer(&count_buf, 0, &(cluster_count as u32).to_le_bytes());
        let count_addr = allocator.wgpu_buffer_device_address(&count_buf).get();

        // Per-cluster template build descriptors. Ids bake to 0 — every
        // instantiate restores the per-mesh global ids via its offsets.
        let (mut max_tris, mut max_verts) = (0u32, 0u32);
        let (mut total_tris, mut total_verts) = (0u32, 0u32);
        let mut descriptors: Vec<
            vk::ClusterAccelerationStructureBuildTriangleClusterTemplateInfoNV,
        > = Vec::with_capacity(cluster_count);
        for cluster in clusters.iter() {
            descriptors.push(
                vk::ClusterAccelerationStructureBuildTriangleClusterTemplateInfoNV {
                    cluster_id: 0,
                    cluster_flags: vk::ClusterAccelerationStructureClusterFlagsNV::default(),
                    triangle_cluster_info_packed: vk::Packed9_9_6_4_4::new(
                        cluster.triangle_count,
                        cluster.vertex_count,
                        0,
                        INDEX_TYPE_32BIT,
                        0,
                    ),
                    base_geometry_index_and_geometry_flags:
                        vk::ClusterAccelerationStructureGeometryIndexAndGeometryFlagsNV {
                            geometry_index_and_geometry_flags: vk::Packed24_5_3::new(
                                0,
                                OPAQUE_GEOMETRY_FLAG,
                            ),
                        },
                    index_buffer_stride: 4,
                    vertex_buffer_stride: 12,
                    geometry_index_and_flags_buffer_stride: 0,
                    opacity_micromap_index_buffer_stride: 0,
                    index_buffer: index_addr + u64::from(cluster.index_offset) * 4,
                    vertex_buffer: ref_verts_addr + u64::from(cluster.vertex_offset) * 12,
                    geometry_index_and_flags_buffer: 0,
                    opacity_micromap_array: 0,
                    opacity_micromap_index_buffer: 0,
                    // 0 = no instantiation bbox clamp — the tess path proves
                    // canonical unit reference verts + world-scale instantiation
                    // work with no limit, and a nonzero limit here (band AABB)
                    // hangs the GPU on the first traced frame (the driver seems
                    // to bake it against the reference geometry).
                    instantiation_bounding_box_limit: 0,
                },
            );
            max_tris = max_tris.max(cluster.triangle_count);
            max_verts = max_verts.max(cluster.vertex_count);
            total_tris += cluster.triangle_count;
            total_verts += cluster.vertex_count;
        }

        let tmpl_stride =
            size_of::<vk::ClusterAccelerationStructureBuildTriangleClusterTemplateInfoNV>() as u64;
        let tmpl_bytes_len = (descriptors.len() as u64) * tmpl_stride;
        // SAFETY: the template info struct is repr(C) POD; a flat byte view is
        // well-defined for upload.
        let tmpl_bytes: &[u8] = unsafe {
            core::slice::from_raw_parts(descriptors.as_ptr().cast::<u8>(), tmpl_bytes_len as usize)
        };
        let src_infos_buf = render_device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("procedural.template.src_infos"),
            size: tmpl_bytes_len,
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::BLAS_INPUT
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        render_queue.write_buffer(&src_infos_buf, 0, tmpl_bytes);
        let src_infos_addr = allocator.wgpu_buffer_device_address(&src_infos_buf).get();

        // Geometry-shape input shared by the template + instantiate size
        // queries and ops. `max_geometry_index_value` must cover the OFFSET
        // (per-mesh global) ids future instantiates apply — conservative 24-bit
        // max; only the size query pays for the slack.
        let mut triangle_input = vk::ClusterAccelerationStructureTriangleClusterInputNV::default()
            .vertex_format(vk::Format::R32G32B32_SFLOAT)
            .max_geometry_index_value((1 << 24) - 1)
            .max_cluster_unique_geometry_count(1)
            .max_cluster_triangle_count(max_tris)
            .max_cluster_vertex_count(max_verts)
            .max_total_triangle_count(total_tris)
            .max_total_vertex_count(total_verts)
            .min_position_truncate_bit_count(0);
        let op_input = vk::ClusterAccelerationStructureOpInputNV {
            p_triangle_clusters: &mut triangle_input as *mut _,
        };
        let tmpl_size_input = vk::ClusterAccelerationStructureInputInfoNV::default()
            .max_acceleration_structure_count(cluster_count as u32)
            .flags(
                vk::BuildAccelerationStructureFlagsKHR::PREFER_FAST_TRACE
                    | vk::BuildAccelerationStructureFlagsKHR::ALLOW_DATA_ACCESS,
            )
            .op_type(vk::ClusterAccelerationStructureOpTypeNV::BUILD_TRIANGLE_CLUSTER_TEMPLATE)
            .op_mode(vk::ClusterAccelerationStructureOpModeNV::IMPLICIT_DESTINATIONS)
            .op_input(op_input);
        let mut tmpl_sizes = vk::AccelerationStructureBuildSizesInfoKHR::default();
        // SAFETY: input fully populated; cluster-AS fn table checked above.
        unsafe {
            cluster_fns
                .get_cluster_acceleration_structure_build_sizes(&tmpl_size_input, &mut tmpl_sizes);
        }

        // Template storage lives as long as the arena — every future
        // instantiate reads it. A plain GpuOnly buffer (small: one topology).
        let template_storage = allocator.create_buffer(
            render_device,
            vk::BufferUsageFlags::STORAGE_BUFFER
                | vk::BufferUsageFlags::ACCELERATION_STRUCTURE_STORAGE_KHR,
            wgpu::BufferUsages::STORAGE,
            tmpl_sizes.acceleration_structure_size.max(1),
            MemoryLocation::GpuOnly,
            "procedural.template.storage",
        );
        let template_storage_addr = allocator.wgpu_buffer_device_address(&template_storage).get();

        let scratch = allocator.create_buffer(
            render_device,
            vk::BufferUsageFlags::STORAGE_BUFFER,
            wgpu::BufferUsages::STORAGE,
            tmpl_sizes.build_scratch_size.max(1) + CLAS_SCRATCH_ALIGN - 1,
            MemoryLocation::GpuOnly,
            "procedural.template.scratch",
        );
        let scratch_addr = align_up(
            allocator.wgpu_buffer_device_address(&scratch).get(),
            CLAS_SCRATCH_ALIGN,
        );

        let addr_array_size = (cluster_count as u64) * 8;
        let dst_addresses = allocator.create_buffer(
            render_device,
            vk::BufferUsageFlags::STORAGE_BUFFER
                | vk::BufferUsageFlags::ACCELERATION_STRUCTURE_STORAGE_KHR
                | vk::BufferUsageFlags::TRANSFER_SRC,
            wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            addr_array_size,
            MemoryLocation::GpuOnly,
            "procedural.template.dst_addresses",
        );
        let dst_addresses_addr = allocator.wgpu_buffer_device_address(&dst_addresses).get();

        let mut encoder = render_device.create_command_encoder(&CommandEncoderDescriptor {
            label: Some("procedural.template.build"),
        });
        let cmd = vk::ClusterAccelerationStructureCommandsInfoNV {
            s_type: vk::ClusterAccelerationStructureCommandsInfoNV::STRUCTURE_TYPE,
            p_next: core::ptr::null_mut(),
            input: tmpl_size_input,
            dst_implicit_data: template_storage_addr,
            scratch_data: scratch_addr,
            dst_addresses_array: vk::StridedDeviceAddressRegionKHR {
                device_address: dst_addresses_addr,
                stride: 8,
                size: addr_array_size,
            },
            dst_sizes_array: vk::StridedDeviceAddressRegionKHR::default(),
            src_infos_array: vk::StridedDeviceAddressRegionKHR {
                device_address: src_infos_addr,
                stride: tmpl_stride,
                size: tmpl_bytes_len,
            },
            src_infos_count: count_addr,
            address_resolution_flags:
                vk::ClusterAccelerationStructureAddressResolutionFlagsNV::default(),
            _marker: core::marker::PhantomData,
        };
        // SAFETY: fn table loaded; encoder open + Vulkan-backed; descriptor
        // strides/addresses reference the buffers created above; no wgpu
        // commands touch this encoder afterward.
        unsafe {
            cmd_build_cluster_acceleration_structures_indirect(&mut encoder, fns, &cmd);
            cmd_global_as_barrier(&mut encoder, render_device, false);
        }
        let build_idx = render_queue.submit([encoder.finish()]);

        // One-time template-address readback (per set, not per mesh).
        let readback = render_device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("procedural.template.addr_readback"),
            size: addr_array_size,
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let mut rb_encoder = render_device.create_command_encoder(&CommandEncoderDescriptor {
            label: Some("procedural.template.addr_copy"),
        });
        rb_encoder.copy_buffer_to_buffer(&dst_addresses, 0, &readback, 0, addr_array_size);
        let rb_idx = render_queue.submit([rb_encoder.finish()]);
        let _ = build_idx;
        readback.slice(..).map_async(wgpu::MapMode::Read, |r| {
            r.expect("procedural: template address readback map failed");
        });
        {
            let _span = tracing::info_span!("procedural.template_build_poll_wait").entered();
            let _ = render_device.wgpu_device().poll(wgpu::PollType::Wait {
                submission_index: Some(rb_idx),
                timeout: None,
            });
        }
        let template_addrs: Vec<u64> = {
            let mapped = readback.slice(..).get_mapped_range();
            mapped
                .chunks_exact(8)
                .map(|c| u64::from_le_bytes(c.try_into().unwrap()))
                .collect()
        };
        readback.unmap();

        // Instantiate sizing for this set — every mesh gets an identical slab.
        let inst_size_input = vk::ClusterAccelerationStructureInputInfoNV::default()
            .max_acceleration_structure_count(cluster_count as u32)
            .flags(
                vk::BuildAccelerationStructureFlagsKHR::PREFER_FAST_TRACE
                    | vk::BuildAccelerationStructureFlagsKHR::ALLOW_DATA_ACCESS,
            )
            .op_type(vk::ClusterAccelerationStructureOpTypeNV::INSTANTIATE_TRIANGLE_CLUSTER)
            .op_mode(vk::ClusterAccelerationStructureOpModeNV::IMPLICIT_DESTINATIONS)
            .op_input(op_input);
        let mut inst_sizes = vk::AccelerationStructureBuildSizesInfoKHR::default();
        // SAFETY: input fully populated; fn table loaded.
        unsafe {
            cluster_fns
                .get_cluster_acceleration_structure_build_sizes(&inst_size_input, &mut inst_sizes);
        }

        self.templates.insert(
            (key, band),
            TemplateSet {
                template_addrs,
                clas_slab_size: align_up(
                    inst_sizes.acceleration_structure_size.max(1),
                    CLAS_STORAGE_ALIGN,
                ),
                op_scratch_size: inst_sizes.build_scratch_size.max(1),
                max_tris,
                max_verts,
                total_tris,
                total_verts,
                count_addr,
                _template_storage: template_storage,
                _index_buf: index_buf,
                _reference_verts_buf: ref_verts_buf,
                _count_buf: count_buf,
            },
        );
        true
    }
}

fn align_up(v: u64, align: u64) -> u64 {
    debug_assert!(align.is_power_of_two());
    (v + align - 1) & !(align - 1)
}

/// `RenderStartup`: insert the procedural resources iff the raw-VK allocator
/// exists (cluster-AS support). The ready channel is inserted in BOTH worlds by
/// [`super::GeometryPlugin`] regardless, so main-world consumers can always join.
pub fn init_procedural_clusters(
    mut commands: Commands,
    render_device: Res<RenderDevice>,
    allocator: Option<Res<Allocator>>,
) {
    let Some(allocator) = allocator else {
        return;
    };
    commands.insert_resource(ProceduralClusters::new(&render_device, &allocator));
}

/// First step of the Fill set: publish this frame's reserved procedural meshes
/// (queued at bind time by `queue_upload_if_needed`) to [`ProceduralMeshRanges`]
/// + [`ProceduralFillQueue`], building any missing template sets.
pub fn drain_pending_procedural(
    render_device: Res<RenderDevice>,
    render_queue: Res<RenderQueue>,
    allocator: Option<Res<Allocator>>,
    fns: Option<Res<ClusterExtensionFns>>,
    mut cluster_meshes: Option<ResMut<ClusterMeshManager>>,
    procedural: Option<ResMut<ProceduralClusters>>,
    clas_arena: Option<Res<ClasArena>>,
    mut ranges: ResMut<ProceduralMeshRanges>,
    mut fill_queue: ResMut<ProceduralFillQueue>,
) {
    let (Some(allocator), Some(fns), Some(cluster_meshes), Some(mut procedural), Some(clas_arena)) =
        (allocator, fns, cluster_meshes.as_deref_mut(), procedural, clas_arena)
    else {
        return;
    };
    let mut clear_encoder: Option<wgpu::CommandEncoder> = None;
    let mut clas_windows: Vec<Range<u64>> = Vec::new();
    for pending in cluster_meshes.pending_procedural.drain(..) {
        let ok = procedural.ensure_template_set(
            &render_device,
            &render_queue,
            &allocator,
            &fns,
            pending.ranges.topology_key,
            pending.ranges.band,
            pending.band_aabb_min,
            pending.band_aabb_max,
        );
        if !ok {
            // Unregistered topology / no cluster-AS support: drop it (error
            // already logged). The mesh stays resident but never traceable.
            continue;
        }
        // The mesh is registered (selector-visible) from THIS point, but its
        // CLAS addresses land at instantiate time — potentially FRAMES later
        // when the fill queue backs up under heavy streaming. Commit + zero
        // its table window NOW so any early reader sees mapped, deterministic
        // zeros instead of unmapped pages (DMA-read translate fault in AS
        // Build) or undefined garbage addresses.
        let window_start = (pending.ranges.cluster_base.0 as u64) * 8;
        let window_len = (pending.ranges.cluster_count as u64) * 8;
        clas_windows.push(window_start..window_start + window_len);
        clear_encoder
            .get_or_insert_with(|| {
                render_device.create_command_encoder(&CommandEncoderDescriptor {
                    label: Some("procedural.reserve.zero_clas_windows"),
                })
            })
            .clear_buffer(
                &clas_arena.cluster_clas_addresses.wgpu_buffer,
                window_start,
                Some(window_len),
            );
        ranges.0.insert(pending.asset_id, pending.ranges);
        fill_queue.0.push(pending.asset_id);
    }
    // One sparse bind + fence wait for every window, then the zeroing submit.
    clas_arena.cluster_clas_addresses.commit_many(clas_windows);
    if let Some(encoder) = clear_encoder {
        render_queue.submit([encoder.finish()]);
    }
}

/// Instantiate every filled procedural mesh's CLAS this frame: one
/// `INSTANTIATE_TRIANGLE_CLUSTER` op per mesh into its own fixed-size slab,
/// destinations written straight into `ClasArena::cluster_clas_addresses`
/// (global table) — no readback, no poll-wait. A leading global barrier makes
/// the fill dispatches' vertex writes visible to the AS build.
pub fn instantiate_procedural(
    render_device: Res<RenderDevice>,
    render_queue: Res<RenderQueue>,
    allocator: Option<Res<Allocator>>,
    fns: Option<Res<ClusterExtensionFns>>,
    cluster_meshes: Option<Res<ClusterMeshManager>>,
    clas_arena: Option<Res<ClasArena>>,
    procedural: Option<ResMut<ProceduralClusters>>,
    ranges: Res<ProceduralMeshRanges>,
    mut queue: ResMut<ProceduralInstantiateQueue>,
    mut retire: ResMut<GpuRetire>,
    ready: Res<ProceduralReadyChannel>,
) {
    if queue.0.is_empty() {
        return;
    }
    let (Some(allocator), Some(fns), Some(cluster_meshes), Some(clas_arena), Some(mut procedural)) =
        (allocator, fns, cluster_meshes, clas_arena, procedural)
    else {
        return;
    };
    if fns.cluster.is_none() {
        return;
    }
    let batch: Vec<AssetId<ClusterMesh>> = queue.0.drain(..).collect();
    let vertex_pool_addr = cluster_meshes.vertex_positions.device_address().get();

    // Gather per-mesh descriptor slices into one upload, sizing scratch as we go.
    struct Op {
        asset_id: AssetId<ClusterMesh>,
        desc_offset: u64,
        desc_len: u64,
        slab_addr: u64,
        scratch_offset: u64,
        addr_table_byte_start: u64,
        cluster_count: u32,
        key_band: (u64, u32),
    }
    let mut descriptors: Vec<vk::ClusterAccelerationStructureInstantiateClusterInfoNV> =
        Vec::new();
    let mut ops: Vec<Op> = Vec::new();
    let inst_stride =
        size_of::<vk::ClusterAccelerationStructureInstantiateClusterInfoNV>() as u64;
    let mut scratch_cursor = 0u64;
    // Sparse commits gathered across the batch → one bind + wait per buffer.
    let mut slab_commits: Vec<Range<u64>> = Vec::new();
    let mut window_commits: Vec<Range<u64>> = Vec::new();
    for asset_id in batch {
        let Some(r) = ranges.0.get(&asset_id) else {
            tracing::warn!(
                target: "bevy_solari",
                "procedural instantiate: {asset_id:?} has no reserved ranges (removed before fill?); skipping",
            );
            continue;
        };
        let key_band = (r.topology_key, r.band);
        // Copy the per-set values out so the mutable slab bookkeeping below
        // doesn't fight the map borrows (template_addrs is ~a few dozen u64s).
        let Some((template_addrs, clas_slab_size, op_scratch_size)) = procedural
            .templates
            .get(&key_band)
            .map(|t| (t.template_addrs.clone(), t.clas_slab_size, t.op_scratch_size))
        else {
            continue; // ensure_template_set already logged.
        };
        let Some(clusters) = procedural
            .topologies
            .get(&r.topology_key)
            .map(|t| Arc::clone(&t.clusters))
        else {
            continue;
        };
        debug_assert_eq!(clusters.len() as u32, r.cluster_count);

        let desc_offset = (descriptors.len() as u64) * inst_stride;
        for (local_id, cluster) in clusters.iter().enumerate() {
            let global_id = r.cluster_base.0.wrapping_add(local_id as u32);
            descriptors.push(vk::ClusterAccelerationStructureInstantiateClusterInfoNV {
                // Templates baked ids 0; restore this mesh's global ids.
                cluster_id_offset: global_id,
                geometry_index_offset_and_reserved: vk::Packed24_8::new(global_id, 0),
                cluster_template_address: template_addrs[local_id],
                vertex_buffer: vk::StridedDeviceAddressNV {
                    start_address: vertex_pool_addr
                        + u64::from(r.vertex_base + cluster.vertex_offset) * 12,
                    stride_in_bytes: 12,
                },
            });
        }

        // Per-mesh fixed slab (reuse an existing one on re-instantiate).
        let slab = if let Some(slab) = procedural.slabs.get(&asset_id) {
            slab.clone()
        } else {
            let slab = procedural
                .slab_alloc
                .allocate_range_aligned(clas_slab_size, CLAS_STORAGE_ALIGN)
                .expect("procedural: CLAS slab virtual-address space exhausted");
            slab_commits.push(slab.clone());
            procedural.slabs.insert(asset_id, slab.clone());
            slab
        };

        // This mesh's window of the global CLAS-address table (the GPU-side
        // copy below lands the instantiated addresses there).
        let addr_table_byte_start = (r.cluster_base.0 as u64) * 8;
        window_commits
            .push(addr_table_byte_start..addr_table_byte_start + (r.cluster_count as u64) * 8);

        let scratch_offset = scratch_cursor;
        scratch_cursor += align_up(op_scratch_size, CLAS_SCRATCH_ALIGN);

        ops.push(Op {
            asset_id,
            desc_offset,
            desc_len: (r.cluster_count as u64) * inst_stride,
            slab_addr: procedural.slab_storage.address + slab.start,
            scratch_offset,
            addr_table_byte_start,
            cluster_count: r.cluster_count,
            key_band,
        });
    }
    if ops.is_empty() {
        return;
    }
    // Commit before any submit touches the pages: slabs are the AS builds'
    // implicit destinations, windows the copy's destination.
    procedural.slab_storage.commit_many(slab_commits);
    clas_arena.cluster_clas_addresses.commit_many(window_commits);

    // Upload the batch's descriptors.
    let desc_bytes_len = (descriptors.len() as u64) * inst_stride;
    // SAFETY: instantiate info is repr(C) POD; flat byte view is valid.
    let desc_bytes: &[u8] = unsafe {
        core::slice::from_raw_parts(descriptors.as_ptr().cast::<u8>(), desc_bytes_len as usize)
    };
    // Reused batch inputs: src_infos (CPU-written), one shared scratch with
    // per-op aligned regions, and the dst-addresses staging the GPU copies
    // into the global table (which lacks AS-storage usage) — no CPU wait.
    let total_clusters: u64 = ops.iter().map(|op| op.cluster_count as u64).sum();
    procedural.batch_bufs.ensure(
        &render_device,
        &allocator,
        &mut retire,
        &render_queue,
        desc_bytes_len,
        scratch_cursor.max(1),
        total_clusters * 8,
    );
    let (src_infos_buf, scratch_buf, dst_addresses_buf) = procedural.batch_bufs.bufs();
    render_queue.write_buffer(src_infos_buf, 0, desc_bytes);
    let src_infos_addr = allocator.wgpu_buffer_device_address(src_infos_buf).get();
    let scratch_base = align_up(
        allocator.wgpu_buffer_device_address(scratch_buf).get(),
        CLAS_SCRATCH_ALIGN,
    );
    let dst_addresses_addr = allocator.wgpu_buffer_device_address(dst_addresses_buf).get();
    // Per-op byte offset into the dst buffer, in `ops` order.
    let mut dst_offsets: Vec<u64> = Vec::with_capacity(ops.len());
    {
        let mut cursor = 0u64;
        for op in &ops {
            dst_offsets.push(cursor);
            cursor += (op.cluster_count as u64) * 8;
        }
    }

    let mut encoder = render_device.create_command_encoder(&CommandEncoderDescriptor {
        label: Some("procedural.instantiate"),
    });
    // Per-op geometry-shape inputs, allocated up front so the pointers each
    // recorded op holds stay valid through record AND submit — a loop-local
    // here corrupts every op but the last on drivers that defer reading the
    // input (symptom: one good patch, N-1 garbage CLAS, ray-traversal hang).
    let mut triangle_inputs: Vec<vk::ClusterAccelerationStructureTriangleClusterInputNV> =
        Vec::with_capacity(ops.len());
    for op in &ops {
        let tset = &procedural.templates[&op.key_band];
        triangle_inputs.push(
            vk::ClusterAccelerationStructureTriangleClusterInputNV::default()
                .vertex_format(vk::Format::R32G32B32_SFLOAT)
                .max_geometry_index_value((1 << 24) - 1)
                .max_cluster_unique_geometry_count(1)
                .max_cluster_triangle_count(tset.max_tris)
                .max_cluster_vertex_count(tset.max_verts)
                .max_total_triangle_count(tset.total_tris)
                .max_total_vertex_count(tset.total_verts)
                .min_position_truncate_bit_count(0),
        );
    }
    // SAFETY: fn table checked; encoder open + Vulkan-backed; every address
    // references live buffers (pools are sparse/stable; slabs committed above);
    // `triangle_inputs` is pre-sized (no reallocation) and outlives the submit;
    // no wgpu commands touch this encoder afterward.
    unsafe {
        // Make the fill dispatches' vertex-pool writes (earlier submits this
        // frame) visible to the AS-build stage.
        cmd_global_as_barrier(&mut encoder, &render_device, false);
        for ((i, op), &dst_offset) in ops.iter().enumerate().zip(&dst_offsets) {
            let tset = &procedural.templates[&op.key_band];
            let op_input = vk::ClusterAccelerationStructureOpInputNV {
                p_triangle_clusters: &mut triangle_inputs[i] as *mut _,
            };
            let inst_input = vk::ClusterAccelerationStructureInputInfoNV::default()
                .max_acceleration_structure_count(op.cluster_count)
                .flags(
                    vk::BuildAccelerationStructureFlagsKHR::PREFER_FAST_TRACE
                        | vk::BuildAccelerationStructureFlagsKHR::ALLOW_DATA_ACCESS,
                )
                .op_type(vk::ClusterAccelerationStructureOpTypeNV::INSTANTIATE_TRIANGLE_CLUSTER)
                .op_mode(vk::ClusterAccelerationStructureOpModeNV::IMPLICIT_DESTINATIONS)
                .op_input(op_input);
            let cmd = vk::ClusterAccelerationStructureCommandsInfoNV {
                s_type: vk::ClusterAccelerationStructureCommandsInfoNV::STRUCTURE_TYPE,
                p_next: core::ptr::null_mut(),
                input: inst_input,
                dst_implicit_data: op.slab_addr,
                scratch_data: scratch_base + op.scratch_offset,
                dst_addresses_array: vk::StridedDeviceAddressRegionKHR {
                    device_address: dst_addresses_addr + dst_offset,
                    stride: 8,
                    size: (op.cluster_count as u64) * 8,
                },
                dst_sizes_array: vk::StridedDeviceAddressRegionKHR::default(),
                src_infos_array: vk::StridedDeviceAddressRegionKHR {
                    device_address: src_infos_addr + op.desc_offset,
                    stride: inst_stride,
                    size: op.desc_len,
                },
                src_infos_count: tset.count_addr,
                address_resolution_flags:
                    vk::ClusterAccelerationStructureAddressResolutionFlagsNV::default(),
                _marker: core::marker::PhantomData,
            };
            cmd_build_cluster_acceleration_structures_indirect(&mut encoder, &fns, &cmd);
            // One barrier per op: the fork never records two cluster-AS ops
            // back-to-back, and the driver appears to need the hazard break
            // even across disjoint scratch/dst regions.
            cmd_global_as_barrier(&mut encoder, &render_device, false);
        }
    }
    render_queue.submit([encoder.finish()]);

    // GPU copy: dst addresses → the global per-cluster CLAS address table (the
    // same slots the direct build fills). Separate wgpu encoder — the trailing
    // barrier above covers AS-write → TRANSFER-read across the submits.
    let mut copy_encoder = render_device.create_command_encoder(&CommandEncoderDescriptor {
        label: Some("procedural.instantiate.copy_addresses"),
    });
    for (op, &dst_offset) in ops.iter().zip(&dst_offsets) {
        copy_encoder.copy_buffer_to_buffer(
            dst_addresses_buf,
            dst_offset,
            &clas_arena.cluster_clas_addresses.wgpu_buffer,
            op.addr_table_byte_start,
            (op.cluster_count as u64) * 8,
        );
    }
    render_queue.submit([copy_encoder.finish()]);

    tracing::debug!(
        "procedural: batch src 0x{src_infos_addr:x}+{desc_bytes_len} scratch 0x{scratch_base:x} dst 0x{dst_addresses_addr:x}+{}",
        total_clusters * 8,
    );

    // Report readiness (instantiate + address copy submitted; the barriers +
    // the BLAS/TLAS passes' own submission order make it traceable this frame).
    if let Ok(mut ready) = ready.0.lock() {
        ready.extend(ops.iter().map(|op| op.asset_id));
    }
}

/// Free a removed procedural mesh's bookkeeping — called from the same
/// asset-event path that frees the mesh pools (`instance_manager`).
pub fn remove_procedural_mesh(
    asset_id: &AssetId<ClusterMesh>,
    procedural: &mut ProceduralClusters,
    ranges: &mut ProceduralMeshRanges,
) {
    procedural.remove(asset_id);
    ranges.0.remove(asset_id);
}
